"""add level.parent_id

Revision ID: 0178fc321776
Revises: 40f89ba4fef0
Create Date: 2023-03-09 13:48:42.487279

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0178fc321776'
down_revision = '40f89ba4fef0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('level', 'hierarchy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'level', 'level', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_obj_id', table_name='obj')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_obj_id', 'obj', ['id'], unique=False)
    op.drop_constraint(None, 'level', type_='foreignkey')
    op.alter_column('level', 'hierarchy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('level', 'parent_id')
    # ### end Alembic commands ###
