"""Added indexes for foreign keys

Revision ID: 20a1d94599de
Revises: e03c04258ba6
Create Date: 2023-12-27 10:35:39.906511

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '20a1d94599de'
down_revision = 'e03c04258ba6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_level_hierarchy_id'), 'level', ['hierarchy_id'], unique=False)
    op.create_index(op.f('ix_level_parent_id'), 'level', ['parent_id'], unique=False)
    op.create_index(op.f('ix_obj_hierarchy_id'), 'obj', ['hierarchy_id'], unique=False)
    op.create_index(op.f('ix_obj_level_id'), 'obj', ['level_id'], unique=False)
    op.create_index(op.f('ix_obj_parent_id'), 'obj', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obj_parent_id'), table_name='obj')
    op.drop_index(op.f('ix_obj_level_id'), table_name='obj')
    op.drop_index(op.f('ix_obj_hierarchy_id'), table_name='obj')
    op.drop_index(op.f('ix_level_parent_id'), table_name='level')
    op.drop_index(op.f('ix_level_hierarchy_id'), table_name='level')
    # ### end Alembic commands ###
