"""Added Nodedata table

Revision ID: 2cdca65512cc
Revises: 20a1d94599de
Create Date: 2024-04-03 13:05:41.331256

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2cdca65512cc'
down_revision = '20a1d94599de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('mo_id', sa.BigInteger(), nullable=True),
    sa.Column('mo_name', sa.String(), nullable=True),
    sa.Column('mo_latitude', sa.Float(), nullable=True),
    sa.Column('mo_longitude', sa.Float(), nullable=True),
    sa.Column('mo_status', sa.String(), nullable=True),
    sa.Column('mo_tmo_id', sa.Integer(), nullable=True),
    sa.Column('mo_p_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['obj.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_data_level_id'), 'node_data', ['level_id'], unique=False)
    op.create_index(op.f('ix_node_data_node_id'), 'node_data', ['node_id'], unique=False)
    op.add_column('level', sa.Column('show_without_children', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('obj', sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obj', 'path')
    op.drop_column('level', 'show_without_children')
    op.drop_index(op.f('ix_node_data_node_id'), table_name='node_data')
    op.drop_index(op.f('ix_node_data_level_id'), table_name='node_data')
    op.drop_table('node_data')
    # ### end Alembic commands ###
