"""Added status for hierarchies.

Revision ID: 35033b020f1f
Revises: 2cdca65512cc
Create Date: 2024-04-03 16:38:31.002350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '35033b020f1f'
down_revision = '2cdca65512cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchy_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('create', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('root_permission_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_permission_id'], ['hierarchy_permission.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'permission')
    )
    op.create_index(op.f('ix_hierarchy_permission_parent_id'), 'hierarchy_permission', ['parent_id'], unique=False)
    op.create_index(op.f('ix_hierarchy_permission_root_permission_id'), 'hierarchy_permission', ['root_permission_id'], unique=False)
    op.add_column('hierarchy', sa.Column('status', sa.String(), server_default='New', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hierarchy', 'status')
    op.drop_index(op.f('ix_hierarchy_permission_root_permission_id'), table_name='hierarchy_permission')
    op.drop_index(op.f('ix_hierarchy_permission_parent_id'), table_name='hierarchy_permission')
    op.drop_table('hierarchy_permission')
    # ### end Alembic commands ###
