"""add tmo_id

Revision ID: 40f89ba4fef0
Revises: da80fa00b692
Create Date: 2022-07-21 15:00:13.518618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '40f89ba4fef0'
down_revision = 'da80fa00b692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj', sa.Column('object_type_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obj', 'object_type_id')
    # ### end Alembic commands ###
