"""added attr_as_parent

Revision ID: 4a625b09c808
Revises: d577db8dddce
Create Date: 2024-12-14 10:34:10.406816

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4a625b09c808'
down_revision = 'd577db8dddce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('attr_as_parent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level', 'attr_as_parent')
    # ### end Alembic commands ###
