"""Add parent id for OBJ

Revision ID: 61b3b510e38a
Revises: a0605800f416
Create Date: 2023-11-29 17:03:38.671986

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '61b3b510e38a'
down_revision = '9c72a253c479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('hierarchy__obj__parent_id', 'obj', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('hierarchy__obj__parent_id', table_name='obj')
    # ### end Alembic commands ###
