"""Deleted object_ids for Obj

Revision ID: 9c72a253c479
Revises: 26d8f9297bc5
Create Date: 2023-09-20 16:55:06.736777

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c72a253c479'
down_revision = '26d8f9297bc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obj', 'object_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj', sa.Column('object_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
