"""Added HierarchyRebuildOrder table

Revision ID: a0605800f416
Revises: 9c72a253c479
Create Date: 2023-11-27 16:32:52.563699

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a0605800f416'
down_revision = '61b3b510e38a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchyrebuildorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hierarchy_id', sa.Integer(), nullable=False),
    sa.Column('on_rebuild', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('hierarchy__obj__parent_id', table_name='obj')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('hierarchy__obj__parent_id', 'obj', ['parent_id'], unique=False)
    op.drop_table('hierarchyrebuildorder')
    # ### end Alembic commands ###
