"""Added new attr 'key_is_empty' for Obj schema

Revision ID: b436f5bb48b0
Revises: 0f01512a1ae2
Create Date: 2024-05-28 13:32:00.654498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b436f5bb48b0'
down_revision = '0f01512a1ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj', sa.Column('key_is_empty', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obj', 'key_is_empty')
    # ### end Alembic commands ###
