"""Added level_id for Obj.

Revision ID: d67acdae848a
Revises: 0178fc321776
Create Date: 2023-03-14 12:00:59.111090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd67acdae848a'
down_revision = '0178fc321776'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obj', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'obj', 'level', ['level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'obj', type_='foreignkey')
    op.drop_column('obj', 'level_id')
    # ### end Alembic commands ###
