"""initial

Revision ID: da80fa00b692
Revises: 
Create Date: 2022-07-21 14:48:37.381665

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da80fa00b692'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchy',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('change_author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('level',
    sa.Column('hierarchy_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('param_type_id', sa.Integer(), nullable=False),
    sa.Column('additional_params_id', sa.Integer(), nullable=True),
    sa.Column('latitude_id', sa.Integer(), nullable=True),
    sa.Column('longitude_id', sa.Integer(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('change_author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['hierarchy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hierarchy_id', 'name', name='_level_hierarchy_id_name')
    )
    op.create_table('obj',
    sa.Column('hierarchy_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('additional_params', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.types.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['hierarchy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['obj.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obj_id'), 'obj', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obj_id'), table_name='obj')
    op.drop_table('obj')
    op.drop_table('level')
    op.drop_table('hierarchy')
    # ### end Alembic commands ###
