"""Added the create_empty_nodes column for Hierarchy table

Revision ID: e03c04258ba6
Revises: a0605800f416
Create Date: 2023-12-13 11:59:49.356501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e03c04258ba6'
down_revision = 'a0605800f416'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hierarchy', sa.Column('create_empty_nodes', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hierarchy', 'create_empty_nodes')
    # ### end Alembic commands ###
